# Generated by Django 2.0.5 on 2018-05-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_novia', models.CharField(max_length=50)),
                ('apellido_novia', models.CharField(max_length=50)),
                ('nombre_novio', models.CharField(max_length=50)),
                ('apellido_novio', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField()),
                ('personas', models.IntegerField()),
                ('costo_bajo', models.IntegerField()),
                ('costo_alto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Camarero',
            fields=[
                ('DNI', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('inicio', models.CharField(max_length=50)),
                ('final', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ceremonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('abogado', models.BooleanField(default=False)),
                ('flores', models.BooleanField(default=False)),
                ('iglesia_fuera', models.BooleanField()),
                ('ceremonia', models.BooleanField(default=False)),
                ('ramo', models.BooleanField(default=False)),
                ('pajecitos', models.BooleanField(default=False)),
                ('carro_antiguo', models.BooleanField(default=False)),
                ('coros', models.BooleanField(default=False)),
                ('boutonnieres', models.BooleanField(default=False)),
                ('servicio_fotografia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fiesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordatorios', models.BooleanField()),
                ('musica', models.CharField(max_length=50)),
                ('tarjetas', models.BooleanField()),
                ('licores', models.BooleanField()),
                ('fuera_ciudad', models.BooleanField()),
                ('flores', models.BooleanField()),
                ('organizadora', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Luna_Miel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viaje_colombia', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pareja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_pre', models.BooleanField()),
                ('argollas', models.BooleanField()),
                ('confirmacion_novia', models.BooleanField()),
                ('docs_novia', models.BooleanField()),
                ('vestido_novia', models.BooleanField()),
                ('maquillaje_peinado', models.BooleanField()),
                ('estetica', models.BooleanField()),
                ('confirmacion_novio', models.BooleanField()),
                ('docs_novio', models.BooleanField()),
                ('vestido_novio', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Regalo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=100)),
                ('titular', models.ManyToManyField(related_name='user', to='app.Invitado')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='sala',
            field=models.ManyToManyField(to='app.Sala'),
        ),
        migrations.AddField(
            model_name='camarero',
            name='mesa',
            field=models.ManyToManyField(to='app.Mesa'),
        ),
    ]
