# Generated by Django 2.0.3 on 2018-03-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camarero',
            fields=[
                ('DNI', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('inicio', models.CharField(max_length=50)),
                ('final', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Regalo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regalo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=100)),
                ('titular', models.ManyToManyField(to='app.Invitado')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='sala',
            field=models.ManyToManyField(to='app.Sala'),
        ),
        migrations.AddField(
            model_name='camarero',
            name='mesa',
            field=models.ManyToManyField(to='app.Mesa'),
        ),
    ]
