# Generated by Django 2.0.3 on 2018-03-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regalo',
            old_name='regalo',
            new_name='tipo',
        ),
    ]
